version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port AMQP
      - "15672:15672"  # Interface de gestion
    networks:
      - mqtt-network

  sender:
    build:
      context: .
      dockerfile: DockerfileSCL
    container_name: sender-capteur-lumiere
    depends_on:
      - rabbitmq
    networks:
      - mqtt-network

  receiver:
    build:
      context: .
      dockerfile: DockerfileRVE
    container_name: receive-volet-electrique
    depends_on:
      - rabbitmq
    networks:
      - mqtt-network

  conteneur:
    build:
      context: .
      dockerfile: DockerfileC
    container_name: conteneur
    depends_on:
      - rabbitmq
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
